destination: /home/qf3l3k/backup
log_directory: /home/qf3l3k/.logs/
log_file: rsync_backup_tool.log
log_level: DEBUG

common_folders:
  - { path: /etc/ufw, pull_entire_folder: true }
  - { path: /etc/fail2ban, pull_entire_folder: true }

hosts:
  htz-host-01.qf3l3k.cloud:
    specific_folders:
      - { path: /data/osmosis/.osmosisd/config, pull_entire_folder: false }
      - { path: /data/osmosis/.osmosisd/data, pull_entire_folder: false }
      - { path: /home/relayer/.hermes, pull_entire_folder: true }
  htz-host-02.qf3l3k.cloud:
    specific_folders:
      - { path: /data/osmosis/.osmosisd/config, pull_entire_folder: false }
      - { path: /data/osmosis/.osmosisd/data, pull_entire_folder: false }
      - { path: /data/beezee/.bze/config, pull_entire_folder: false }
      - { path: /data/beezee/.bze/data, pull_entire_folder: false }
      - { path: /home/relayer/.hermes, pull_entire_folder: true }
  htz-host-03.qf3l3k.cloud:
    specific_folders:
      - { path: /data/osmosis/.osmosisd/config, pull_entire_folder: false }
      - { path: /data/osmosis/.osmosisd/data, pull_entire_folder: false }
      - { path: /home/relayer/.hermes, pull_entire_folder: true }

