destination: /home/qf3l3k/backup
log_directory: /home/qf3l3k/.logs/
log_file: rsync_backup_tool.log
log_level: DEBUG

common_folders:
  - { path: /etc/fail2ban, pull_entire_folder: true }
  - { path: /etc/ssh, pull_entire_folder: true }
  - { path: /etc/ufw, pull_entire_folder: true }

hosts:
  htz-host-01.qf3l3k.cloud:
    specific_folders:
      - { path: /data/osmosis/.osmosisd/config, pull_entire_folder: false }
      - { path: /data/osmosis/.osmosisd/data, pull_entire_folder: false }
      - { path: /etc/caddy, pull_entire_folder: true }
      - { path: /home/relayer/.hermes, pull_entire_folder: true }
      - { path: /home/entangle/.entangled/config, pull_entire_folder: false }
      - { path: /home/entangle/.entangled/data, pull_entire_folder: false }
  htz-host-02.qf3l3k.cloud:
    specific_folders:
      - { path: /data/noble/.noble/config, pull_entire_folder: false }
      - { path: /data/noble/.noble/data, pull_entire_folder: false }
      - { path: /data/osmosis/.osmosisd/config, pull_entire_folder: false }
      - { path: /data/osmosis/.osmosisd/data, pull_entire_folder: false }
      - { path: /data/beezee/.bze/config, pull_entire_folder: false }
      - { path: /data/beezee/.bze/data, pull_entire_folder: false }
      - { path: /etc/caddy, pull_entire_folder: true }
      - { path: /home/relayer/.hermes, pull_entire_folder: true }
  htz-host-03.qf3l3k.cloud:
    specific_folders:
      - { path: /data/osmosis/.osmosisd/config, pull_entire_folder: false }
      - { path: /data/osmosis/.osmosisd/data, pull_entire_folder: false }
      - { path: /etc/caddy, pull_entire_folder: true }
      - { path: /home/relayer/.hermes, pull_entire_folder: true }
  ovh-host-01.qf3l3k.cloud:
    specific_folders:
      - { path: /home/carbon/.carbon/config, pull_entire_folder: false }
      - { path: /home/carbon/.carbon/data, pull_entire_folder: false }
      - { path: /home/nomic/.orga-wallet, pull_entire_folder: false }
      - { path: /home/nomic/.nomic-stakenet-3/, pull_entire_folder: false }
      - { path: /home/nomic/.nomic-stakenet-3/frost, pull_entire_folder: false }
      - { path: /home/nomic/.nomic-stakenet-3/frost_aux, pull_entire_folder: false }
      - { path: /home/nomic/.nomic-stakenet-3/signer, pull_entire_folder: false }
      - { path: /home/nomic/.nomic-stakenet-3/tendermint/config, pull_entire_folder: false }
      - { path: /home/nomic/.nomic-stakenet-3/tendermint/data, pull_entire_folder: false }
  ovh-host-02.qf3l3k.cloud:
    specific_folders:
      - { path: /home/acre/.acred/config, pull_entire_folder: false }
      - { path: /home/acre/.acred/data, pull_entire_folder: false }
      - { path: /home/cnho/.cnho/config, pull_entire_folder: false }
      - { path: /home/cnho/.cnho/data, pull_entire_folder: false }
      - { path: /home/provenance/.config/Provenance/config, pull_entire_folder: false }
      - { path: /home/provenance/.config/Provenance/data, pull_entire_folder: false }
      - { path: /home/sifchain/.sifnoded/config, pull_entire_folder: false }
      - { path: /home/sifchain/.sifnoded/data, pull_entire_folder: false }
      - { path: /home/unification/.und_mainchain/config, pull_entire_folder: false }
      - { path: /home/unification/.und_mainchain/data, pull_entire_folder: false }
  ovh-host-03.qf3l3k.cloud:
    specific_folders:
      - { path: /home/decentr/.decentr/config, pull_entire_folder: false }
      - { path: /home/decentr/.decentr/data, pull_entire_folder: false }
      - { path: /home/joltify/.joltify/config, pull_entire_folder: false }
      - { path: /home/joltify/.joltify/data, pull_entire_folder: false }
      - { path: /home/konstellation/.knstld/config, pull_entire_folder: false }
      - { path: /home/konstellation/.knstld/data, pull_entire_folder: false }
      - { path: /home/lum/.lumd/config, pull_entire_folder: false }
      - { path: /home/lum/.lumd/data, pull_entire_folder: false }
      - { path: /home/planq/.planqd/config, pull_entire_folder: false }
      - { path: /home/planq/.planqd/data, pull_entire_folder: false }
      - { path: /home/sentinel/.sentinelhub/config, pull_entire_folder: false }
      - { path: /home/sentinel/.sentinelhub/data, pull_entire_folder: false }
  ovh-host-04.qf3l3k.cloud:
    specific_folders:
      - { path: /home/andromeda/.andromeda/config, pull_entire_folder: false }
      - { path: /home/andromeda/.andromeda/data, pull_entire_folder: false }
      - { path: /home/beezee/.bze/config, pull_entire_folder: false }
      - { path: /home/beezee/.bze/data, pull_entire_folder: false }
      - { path: /home/desmos/.desmos/config, pull_entire_folder: false }
      - { path: /home/desmos/.desmos/data, pull_entire_folder: false }
      - { path: /home/emoney/.emd/config, pull_entire_folder: false }
      - { path: /home/emoney/.emd/data, pull_entire_folder: false }
      - { path: /home/meme/.memed/config, pull_entire_folder: false }
      - { path: /home/meme/.memed/data, pull_entire_folder: false }
      - { path: /home/penumbra/.penumbra/network_data/node0/cometbft/config, pull_entire_folder: false }
      - { path: /home/penumbra/.penumbra/network_data/node0/cometbft/data, pull_entire_folder: false }
      - { path: /home/penumbra/.penumbra/.local/share/pcli, pull_entire_folder: false }
      - { path: /home/rizon/.rizon/config, pull_entire_folder: false }
      - { path: /home/rizon/.rizon/data, pull_entire_folder: false }
      - { path: /home/starname/.starnamed/config, pull_entire_folder: false }
      - { path: /home/starname/.starnamed/data, pull_entire_folder: false }
  ovh-host-05.qf3l3k.cloud:
    specific_folders:
      - { path: /etc/caddy, pull_entire_folder: true }
      - { path: /home/tenderduty/.tenderduty, pull_entire_folder: false }
  ovh-host-06.qf3l3k.cloud:
    specific_folders:
      - { path: /home/bitsong/.bitsongd/config, pull_entire_folder: false }
      - { path: /home/bitsong/.bitsongd/data, pull_entire_folder: false }
      - { path: /home/firmachain/.firmachain/config, pull_entire_folder: false }
      - { path: /home/firmachain/.firmachain/data, pull_entire_folder: false }
      - { path: /home/gitopia/.gitopia/config, pull_entire_folder: false }
      - { path: /home/gitopia/.gitopia/data, pull_entire_folder: false }
      - { path: /home/kichain/.kid/config, pull_entire_folder: false }
      - { path: /home/kichain/.kid/data, pull_entire_folder: false }
      - { path: /home/omniflix/.omniflixhub/config, pull_entire_folder: false }
      - { path: /home/omniflix/.omniflixhub/data, pull_entire_folder: false }
  ovh-host-07.qf3l3k.cloud:
    specific_folders:
      - { path: /home/bluzelle/.curium/config, pull_entire_folder: false }
      - { path: /home/bluzelle/.curium/data, pull_entire_folder: false }
      - { path: /home/dyson/.dyson/config, pull_entire_folder: false }
      - { path: /home/dyson/.dyson/data, pull_entire_folder: false }
      - { path: /home/fetchai/.fetchd/config, pull_entire_folder: false }
      - { path: /home/fetchai/.fetchd/data, pull_entire_folder: false }
      - { path: /home/jackal/.canine/config, pull_entire_folder: false }
      - { path: /home/jackal/.canine/data, pull_entire_folder: false }
      - { path: /home/panacea/.panacea/config, pull_entire_folder: false }
      - { path: /home/panacea/.panacea/data, pull_entire_folder: false }
  ovh-host-09.qf3l3k.cloud:
    specific_folders:
      - { path: /etc/caddy, pull_entire_folder: true }
      - { path: /home/t-atomone/.atomone/config, pull_entire_folder: false }
      - { path: /home/t-atomone/.atomone/data, pull_entire_folder: false }
      - { path: /home/t-beezee/.tbze/config, pull_entire_folder: false }
      - { path: /home/t-beezee/.tbze/data, pull_entire_folder: false }
      - { path: /home/t-jackal/.canine/config, pull_entire_folder: false }
      - { path: /home/t-jackal/.canine/data, pull_entire_folder: false }
      - { path: /home/t-kopi/.kopid/config, pull_entire_folder: false }
      - { path: /home/t-kopi/.kopid/data, pull_entire_folder: false }
      - { path: /home/t-kichain/.kid/config, pull_entire_folder: false }
      - { path: /home/t-kichain/.kid/data, pull_entire_folder: false }
      - { path: /home/t-lava/.lava/config, pull_entire_folder: false }
      - { path: /home/t-lava/.lava/data, pull_entire_folder: false }
      - { path: /home/t-ojo/.ojo/config, pull_entire_folder: false }
      - { path: /home/t-ojo/.ojo/data, pull_entire_folder: false }
      - { path: /home/t-omniflix/.omniflixhub/config, pull_entire_folder: false }
      - { path: /home/t-omniflix/.omniflixhub/data, pull_entire_folder: false }
      - { path: /home/t-soar/.soarchain/config, pull_entire_folder: false }
      - { path: /home/t-soar/.soarchain/data, pull_entire_folder: false }
      - { path: /home/t-struct/.structs/config, pull_entire_folder: false }
      - { path: /home/t-struct/.structs/data, pull_entire_folder: false }
  ovh-host-10.qf3l3k.cloud:
    specific_folders:
      - { path: /home/crescent/.crescent/config, pull_entire_folder: false }
      - { path: /home/crescent/.crescent/data, pull_entire_folder: false }
      - { path: /home/composable/.banksy/config, pull_entire_folder: false }
      - { path: /home/composable/.banksy/data, pull_entire_folder: false }
      - { path: /home/ixo/.ixod/config, pull_entire_folder: false }
      - { path: /home/ixo/.ixod/data, pull_entire_folder: false }
      - { path: /home/oraichain/.oraid/config, pull_entire_folder: false }
      - { path: /home/oraichain/.oraid/data, pull_entire_folder: false }
      - { path: /home/quasar/.quasarnode/config, pull_entire_folder: false }
      - { path: /home/quasar/.quasarnode/data, pull_entire_folder: false }
      - { path: /home/shido/.shidod/config, pull_entire_folder: false }
      - { path: /home/shido/.shidod/data, pull_entire_folder: false }
      - { path: /home/xpla/.xpla/config, pull_entire_folder: false }
      - { path: /home/xpla/.xpla/data, pull_entire_folder: false }
  ovh-host-11.qf3l3k.cloud:
    specific_folders:
      - { path: /home/bitcanna/.bcna/config, pull_entire_folder: false }
      - { path: /home/bitcanna/.bcna/data, pull_entire_folder: false }
      - { path: /home/kyve/.kyve/config, pull_entire_folder: false }
      - { path: /home/kyve/.kyve/data, pull_entire_folder: false }
      - { path: /home/source/.source/config, pull_entire_folder: false }
      - { path: /home/source/.source/data, pull_entire_folder: false }
      - { path: /home/stargaze/.starsd/config, pull_entire_folder: false }
      - { path: /home/stargaze/.starsd/data, pull_entire_folder: false }
      - { path: /home/teritori/.teritorid/config, pull_entire_folder: false }
      - { path: /home/teritori/.teritorid/data, pull_entire_folder: false }
      - { path: /home/terp/.terp/config, pull_entire_folder: false }
      - { path: /home/terp/.terp/data, pull_entire_folder: false }
  ovh-host-12.qf3l3k.cloud:
    specific_folders:
      - { path: /home/mantle/.mantleNode/config, pull_entire_folder: false }
      - { path: /home/mantle/.mantleNode/data, pull_entire_folder: false }
      - { path: /home/cheqd/.cheqdnode/config, pull_entire_folder: false }
      - { path: /home/cheqd/.cheqdnode/data, pull_entire_folder: false }
      - { path: /home/furya/.furyad/config, pull_entire_folder: false }
      - { path: /home/furya/.furyad/data, pull_entire_folder: false }
      - { path: /home/neutaro/.Neutaro/config, pull_entire_folder: false }
      - { path: /home/neutaro/.Neutaro/data, pull_entire_folder: false }
      - { path: /home/odin/.odin/config, pull_entire_folder: false }
      - { path: /home/odin/.odin/data, pull_entire_folder: false }
      - { path: /home/tenet/.tenetd/config, pull_entire_folder: false }
      - { path: /home/tenet/.tenetd/data, pull_entire_folder: false }
  ovh-host-13.qf3l3k.cloud:
    specific_folders:
      - { path: /home/atomone/.atomone/config, pull_entire_folder: false }
      - { path: /home/atomone/.atomone/data, pull_entire_folder: false }
      - { path: /home/bitbadges/.bitbadgeschain/config, pull_entire_folder: false }
      - { path: /home/bitbadges/.bitbadgeschain/data, pull_entire_folder: false }
      - { path: /home/kopi/.kopid/config, pull_entire_folder: false }
      - { path: /home/kopi/.kopid/data, pull_entire_folder: false }
      - { path: /home/passage/.passage/config, pull_entire_folder: false }
      - { path: /home/passage/.passage/data, pull_entire_folder: false }
      - { path: /home/selfchain/.selfchain/config, pull_entire_folder: false }
      - { path: /home/selfchain/.selfchain/data, pull_entire_folder: false }
  ovh-host-14.qf3l3k.cloud:
    specific_folders:
      - { path: /home/kava/.kava/config, pull_entire_folder: false }
      - { path: /home/kava/.kava/data, pull_entire_folder: false }
      - { path: /home/namada/.local/share/namada/namada.5f5de2dd1b88cba30586420/cometbft/config, pull_entire_folder: false }
      - { path: /home/namada/.local/share/namada/namada.5f5de2dd1b88cba30586420/cometbft/data, pull_entire_folder: false }
      - { path: /home/synternet/.amber/config, pull_entire_folder: false }
      - { path: /home/synternet/.amber/data, pull_entire_folder: false }
  con-node-02.qf3l3k.cloud:
    specific_folders:
      - { path: /home/waves/.local/etc, pull_entire_folder: true }
  con-node-03.qf3l3k.cloud:
    specific_folders:
      - { path: /etc/caddy, pull_entire_folder: true }
      - { path: /home/pactus/pactus/wallets, pull_entire_folder: false }